spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

cors:
  url: ${CORS_URL}